# Generated by Django 3.0.6 on 2020-06-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('accessory', 'Accessory'), ('computer', 'Computer'), ('electronic', 'Electronic'), ('fashion', 'Fashion'), ('phones', 'Phone')], max_length=30)),
                ('price', models.IntegerField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('product_state', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=5)),
                ('image1', models.ImageField(upload_to='product images')),
                ('image2', models.ImageField(upload_to='product images')),
                ('image3', models.ImageField(upload_to='product images')),
                ('description', models.TextField()),
                ('delivery_description', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ['-time'],
            },
        ),
    ]
